import type { Metadata } from 'next'
import clsx from 'clsx'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'shadow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx('bg-background text-text')}>{children}</body>
    </html>
  )
}
