name: scanMdFile

permissions:
  actions: write
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "content/posts/**"
  
  workflow_dispatch:


jobs:
  scanMdFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install Dependencies
        run: |
          npm install
          npm install marked
          npm install marked-highlight
          npm install highlight.js
          npm install dompurify
          npm install jsdom

      - name: Run scanMdFile
        run: |
          node ./content/scripts/index.js
      
      - name: Set git config
        run: |
          git config user.name 192114
          git config user.email shadowSun192114@gmail.com

      - name: Push
        run: |
          git add .
          git commit -m "update posts json file"
          git push
