name: scanMdFile

permissions:
  actions: write
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "content/posts/**"
  
  workflow_dispatch:
  

jobs:
  scanMdFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install Dependencies
        run: |
          npm install
          npm install marked

      - name: Run scanMdFile
        run: |
          node ./content/scripts/index.js

      - name: Push
        run: |
          git config user.name 192114
          git config user.email shadowSun192114@gmail.com
          git add .
          git commit -m "update posts json file"
          git push
