name: scanMdFile
on: 
  push:
    branches:
      - main
    paths:
      - 'content/posts/**'

jobs:
  scanMdFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install Dependencies
        run: |
          npm install
          npm install marked
          node ./content/scripts/index.js
